# Generated by Django 3.2.2 on 2021-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='average_rating',
        ),
    ]
