# Generated by Django 3.2.2 on 2021-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='designer',
            field=models.CharField(max_length=50),
        ),
    ]
