# Generated by Django 3.2.2 on 2021-05-14 18:54

from django.db import migrations, models
import raterprojectapi.models.gamer


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_remove_game_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='currently_playing_image',
            field=models.ImageField(blank=True, upload_to=raterprojectapi.models.gamer.upload_to),
        ),
    ]
