# Generated by Django 3.2.2 on 2021-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_alter_game_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
