# Generated by Django 3.2.2 on 2021-05-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0004_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category_id',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(through='raterprojectapi.GameCategory', to='raterprojectapi.Category'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterprojectapi.category'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterprojectapi.game'),
        ),
    ]
