# Generated by Django 3.2.2 on 2021-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0005_auto_20210512_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(through='raterprojectapi.GameCategory', to='raterprojectapi.Category'),
        ),
    ]
